guides/using-python-with-github-actions
name: Python application
on:
pull_request:
branches: [ &quot;main&quot; ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Set up Python 3.10
uses: actions/setup-python@v3
with:
python-version: &quot;3.10&quot;
- name: Test
run: cd ./sources &amp;&amp; python -m unittest test_calc.py
